Fix user comments on gemini api (#5987)
* fix "TypeError: CachedSourceFinderHandler.get() missing 1 required positional argument: 'cache_key'" by handling missing cache key.

* Cleanup the code.

* Update Gemini user authentication to use user_key instead of user_password. Add the migration for that.

* Fix ZTF catalog matching warning message formatting and refactor parameters in finding charts function.

* Update Gemini API to allow user to choose a custom group_name or the default will use object ID.

* Small typo fix.

* Update user_key retrieval to fallback on user_password for compatibility and remove migration.